#This is the configuration file of QuickSumo, Here you will be able to modify
#Messages and some other settings.

Prefix:
  enabled: true
  value: "&8▎ &e&lSUMO &8▶&f "

#Command permissions
Permissions:
  sumo_start: "sumo.start"
  sumo_setup: "sumo.admin"

#This is used to save and load players inventory before entering the tournament and after
Inventory_Saver:
  enabled: true

Settings:
  #minimum amount of players to start (can't be less than two)
  min_players: 2
  #you can use -1 value for "max_players" to make it unlimited
  max_players: 12
  #start the tournament after x second(s)
  count_down: 30
  #start a round after x second(s)
  round_count_down: 5
  #wait x seconds before starting a new round
  round_delay: 2

Messages:
  help_message:
    - "&7/Sumo &eStart &7Start sumo tournament"
    - "&7/Sumo &eSetLocation &7<LocationType> &7Set targeted location"
    - "&7/Sumo &eReload &7Reload configuration file and stop running tournament"
  invalid_args: "&cInvalid arguments"
  no_permission: "&cSorry, but you're not allowed to execute this command"
  player_only: "&cOnly players can execute this command"
  location_set: "&7Location &e<loc> &7has been set to your location"
  invalid_location: "&cInvalid location type!"
  modify_location_failed: "&cYou can't modify locations while the tournament is running"
  start_failed: "&cFailed to start sumo tournament, one or more setting is not set"
  tournament_already_started: "&cTournament already started"
  starting_in: "&7Starting tournament in &e{seconds} second(s)"
  no_tournament: "&cThere is no tournament running"
  invalid_min_players: "&cFailed to start sumo tournament, incorrect &emin_players &cvalue"
  click_hover: "&aClick me"
  round_count_down: "&7Starting in &e{seconds} second(s)"
  round_started: "&7Round &eStarted!"




Broadcasts:
  tournament_started:
    - "&e{player} &7has started a &e&lSUMO Tournament"
    - "Type &e/Sumo join &7or &a[CLICK ME]"
  sumo_join: "&e{player} &7has joined"
  round_start: "&7Round &e#{roundNumber}: &e{player1} &7VS &e{player2}"
  tournament_start: "&7Tournament has &eStarted!"
  round_win: "&7Player &e{winner} &7won against &c{loser}"


Actionbar:
  waiting: "&eWaiting for players..."

