name: QuickSumo
author: Cobeine
version: 0.1-INDEV
main: me.cobeine.sumo.Core
website: "https://github.com/Cobeine/"

commands:
  QuickSumo:
    aliases: [qSumo,qs,sumo]
    permission: QuickSumo.Setup
    description: "Setup command for QuickSumo"